baseURL = "https://www.rinfinance.com/"
languageCode = "en-us"
title = "R/Finance Conference"

theme = ["hugo-rfinance-theme", "hugo-universal-theme"]

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "About"
    url  = "/about/"
    weight = 2

[[menu.main]]
    identifier = "cfp"
    name = "Call for Presenters"
    url  = "/cfp/"
    weight = 3

[[menu.main]]
    identifier = "sponsorship"
    name = "Sponsors"
    url  = "/sponsors/"
    weight = 4

[[menu.main]]
    identifier = "coc"
    name = "Code of Conduct"
    url  = "/coc/"
    weight = 5

[[menu.main]]
    identifier = "diversity"
    name = "Diversity"
    url  = "/diversity/"
    weight = 5

[params.welcome]
    title = "Applied Finance with R"

[params.features]
    enable = false

[params.committee]
    enable_footer = true

[params]
    style = "blue"
    logo = "img/Rfinance_logo.png"
